" VIMRC 
" @author=gablaterreur
"
set clipboard=unnamedplus
set encoding=UTF-8
set noerrorbells
set termguicolors
set shortmess+=I
set showcmd
set laststatus=1
set autoread

" Easuer change buffers
set wildmenu
set wildmode=longest:full,full
set path+=**

" Backup files
if !isdirectory($XDG_STATE_HOME . "/vim/backup")
  call mkdir($XDG_STATE_HOME . "/vim/backup", "p")
endif
if !isdirectory($XDG_STATE_HOME . "/vim/backupf")
  call mkdir($XDG_STATE_HOME . "/vim/backupf", "p")
endif
set backup
set backupdir=$XDG_STATE_HOME/vim/backup//
set directory=$XDG_STATE_HOME/vim/backupf//

" Cursor
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Line numbers
set number
set relativenumber

" Tabs & spaces
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set smarttab
set smartindent

" Highlights
set hlsearch
set incsearch
set ignorecase
set smartcase

" Bindings
nnoremap <Leader>b :buffers<CR>:buffer<Space>
nnoremap <Leader>t :term<CR>

syntax enable
filetype plugin indent on

" call plug#begin()
" 
" Plug 'tpope/vim-fugitive'
" 
" call plug#end()

colorscheme habamax
